package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import model.Invoice;
import model.InvoiceItem;
import service.InvoiceService;
import util.UserSession;

public class InvoiceUI {

    public static void main(String[] args) {
        // Security Check: Ensure a warehouse manager is logged in
        if (UserSession.loggedInShopId == 0) {
            JOptionPane.showMessageDialog(null, "Security Alert: Please login first!");
            return;
        }

        int currentShopId = UserSession.loggedInShopId;

        // Setup the Main Frame
        JFrame frame = new JFrame("Warehouse " + currentShopId + " - Billing & Checkout");
        frame.setSize(800, 500);
        frame.setLayout(new BorderLayout(10, 10));
        frame.setLocationRelativeTo(null);

        // --- Top Panel: Customer & Product Entry ---
        JPanel inputPanel = new JPanel(new GridLayout(4, 2, 10, 10));
        inputPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JTextField customerIdField = new JTextField();
        JTextField productIdField = new JTextField();
        JTextField quantityField = new JTextField();
        JTextField priceField = new JTextField(); // Temporary manual price entry for simplicity

        inputPanel.add(new JLabel("Customer ID:"));
        inputPanel.add(customerIdField);
        inputPanel.add(new JLabel("Product ID:"));
        inputPanel.add(productIdField);
        inputPanel.add(new JLabel("Quantity to Sell:"));
        inputPanel.add(quantityField);
        inputPanel.add(new JLabel("Price Per Item:"));
        inputPanel.add(priceField);

        // --- Center Panel: The Shopping Cart (Table) ---
        String[] cols = {"Product ID", "Quantity", "Price", "Subtotal"};
        DefaultTableModel cartModel = new DefaultTableModel(cols, 0);
        JTable cartTable = new JTable(cartModel);
        JScrollPane scrollPane = new JScrollPane(cartTable);

        // --- Bottom Panel: Buttons and Total ---
        JPanel btnPanel = new JPanel();
        JButton addToCartBtn = new JButton("Add to Cart");
        JButton generateBillBtn = new JButton("Generate Bill");
        JLabel totalLabel = new JLabel("Total Amount: 0.0");
        totalLabel.setFont(new Font("Arial", Font.BOLD, 14));

        btnPanel.add(addToCartBtn);
        btnPanel.add(generateBillBtn);
        btnPanel.add(totalLabel);

        // --- Actions ---

        // 1. Add to Cart Action
        addToCartBtn.addActionListener(e -> {
            try {
                int prodId = Integer.parseInt(productIdField.getText());
                int qty = Integer.parseInt(quantityField.getText());
                double price = Double.parseDouble(priceField.getText());
                double subtotal = qty * price;

                // Add row to the visual cart
                cartModel.addRow(new Object[]{prodId, qty, price, subtotal});

                // Update the visual total
                double currentTotal = 0;
                for (int i = 0; i < cartModel.getRowCount(); i++) {
                    currentTotal += (double) cartModel.getValueAt(i, 3);
                }
                totalLabel.setText("Total Amount: " + currentTotal);

                // Clear product fields for the next item
                productIdField.setText("");
                quantityField.setText("");
                priceField.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Please enter valid numbers for Product ID, Quantity, and Price.");
            }
        });

        // 2. Generate Bill Action
        generateBillBtn.addActionListener(e -> {
            try {
                int customerId = Integer.parseInt(customerIdField.getText());

                // Calculate final total from the cart
                double finalTotal = 0;
                List<InvoiceItem> itemsList = new ArrayList<>();

                for (int i = 0; i < cartModel.getRowCount(); i++) {
                    int pId = (int) cartModel.getValueAt(i, 0);
                    int qty = (int) cartModel.getValueAt(i, 1);
                    double sub = (double) cartModel.getValueAt(i, 3);
                    
                    finalTotal += sub;
                    
                    // Create the InvoiceItem object (IDs will be generated by the database)
                    InvoiceItem item = new InvoiceItem(0, 0, pId, qty, sub);
                    itemsList.add(item);
                }

                if (itemsList.isEmpty()) {
                    JOptionPane.showMessageDialog(frame, "Cart is empty!");
                    return;
                }

                // Create the main Invoice object
                Invoice invoice = new Invoice(0, currentShopId, customerId, finalTotal);

                // Send to the service layer for the database transaction
                InvoiceService service = new InvoiceService();
                boolean success = service.createInvoiceWithItems(invoice, itemsList);

                if (success) {
                    JOptionPane.showMessageDialog(frame, "Bill Generated Successfully! Stock has been updated.");
                    // Clear the cart and reset
                    cartModel.setRowCount(0);
                    customerIdField.setText("");
                    totalLabel.setText("Total Amount: 0.0");
                } else {
                    JOptionPane.showMessageDialog(frame, "Checkout Failed! Please check if the Customer ID exists and if you have enough stock.", "Transaction Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Please enter a valid Customer ID.");
            }
        });

        // Add everything to the frame
        frame.add(inputPanel, BorderLayout.NORTH);
        frame.add(scrollPane, BorderLayout.CENTER);
        frame.add(btnPanel, BorderLayout.SOUTH);

        frame.setVisible(true);
    }
}